title: WebVR for 3D Graphics and Music
baseurl: http://opentechschool-brussels.github.io/webVR-for-3D-graphics-and-music

markdown: redcarpet
redcarpet:
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "strikethrough", "autolink"]

pygments: true

permalink: title.html
